SQUASH: Legacy camera
Camera: Restore camera HALv1 support [1/2]

Revert "Camera: remove the camera device version check during statusCallback"
This reverts commit b8259798dc04226eb09114527cb124060fbf335b.

Revert "Camera: Remove old recording path support"
This reverts commit b8ed8efe811cf64d4afb190fb1f522a29be27bcf.

Revert "Camera: Remove all camera HALv1 code"
This reverts commit a976df84a463b83f5093ee34e00a726779f34308.

Adapt to changes in camera2 api since the removal of HALv1 support.

Change-Id: I4f1f505be8aaf97f5c68856806823c529a5d5ec9

Camera: Add extensions to CameraClient

This change includes the following gerrits:

  # This is a combination of 4 commits.
  # The first commit's message is:
  Camera: Enable Histogram feature.
  Link the histogram enable/disable commands from
  application to the HAL layer.
  Change-Id: I510c4e1798285ed1315bfb0d234fa76090659ba2

  # This is the 2nd commit message:
  Camera: Add support for ZSL burst mode.
  Added ability to set number of snapshots in burst mode.
  Change-Id: Ie0e7c8c0117b7adc985cfc92df79747ee6a5ea51

  # This is the 3rd commit message:
  CameraService: Adds support for longshot mode
  - This change introduces additional functionality inside
    CameraClient for supporting continuous compressed data
    callbacks. This is needed for 'Burst/Long shot' mode
    where we could have indefinite number of callbacks after
    capture is triggered.
  (cherrypicked from commit e4f502aa7cbe8875e8a1589024cdcf227c228a2b)
  Change-Id: Ia18ca9bdda7736c679db557e510870115089537a

  # This is the 4th commit message:
  CameraClient: Enables meta data notifications.
  Adds the needed functionality for enabling/disabling
  metadata messages depending on the camera client
  commands.
  Change-Id: I39d632b4742e83df5db5f86b12742aefc2480dfc
  Cherrypicked from 25bd97f5ec30e7942c3b1fdc96115da6028736f0

Change-Id: Ie930d20c962593e40a0767f9cf7d4385df8e2561

Camera: CameraHardwareInterface changes to support Extended FD

Added QDataCallback definition to pass the extended QCameraFrameMetadata
fields from HIDL to framework.

Change-Id: Idece64f22dd6ee3713c7db658b8583854086a1d8

Camera: Miscellaneous fixes in QDataCallback and binder death scenarios.

This is a squash of following changes:

                      Change-ID                          Subject
   ------------------------------------------------------------------------------
1) I6fc5fa6e01c002bc46be058fcd977be14cae0270    CameraService: Fix deadlock in binder death cleanup
2) I7239f6eb6a9dec67393e11b83d0ef6c986215940    Camera: CameraHardwareInterface: Releasing mHIDLMemoryMapLock in QdataCallback
3) I3fbe4ad836c2abbd512e3728cf49f9424b726ba0	Camera:CameraService: Added lock on mHIDLMemPoolId in QDataCallback

CRs-Fixed: 2246547

CameraService: Fix deadlock in binder death cleanup
Issue:
In the event of a binder death, there is a chance of deadlock
due to recursive lock acquisition in the death handling sequence.
Fix:
Clear evicted client list before acquiring service lock.

Change-Id: I6fc5fa6e01c002bc46be058fcd977be14cae0270

Camera: CameraHardwareInterface: Releasing mHIDLMemoryMapLock in QdataCallback
Issue: Camera is getting stuck due to mHIDLMemoryMapLock when called for
       QDataCallback then  unregister  memory from HAL.
Solution: Releasing mHIDLMemoryMapLock after reading mHIDLMemoryMap variable

Change-Id: I7239f6eb6a9dec67393e11b83d0ef6c986215940

Camera:CameraService: Added lock on mHIDLMemPoolId in QDataCallback..
securing mHIDLMemPoolId (unordered_map variable) from multithreading.

Change-Id: I3fbe4ad836c2abbd512e3728cf49f9424b726ba0

camera: Only link and use vendor.qti.hardware.camera.device if specified

Set TARGET_USES_QTI_CAMERA_DEVICE to link and use

This commit squashes:
  camera: Convert lineage product variables to soong config variables
  Change-Id: Id55eef9838964a420f0eb100e0e9eaee9611ce51

Change-Id: I3a82412190b8918248bdd7a1d823777debd67173

nuplayer: Avoid crash when codec fails to load

 * Remove unnecessary check condition.

Change-Id: I3267a0c13165d74a2ea90333b42f000b51ace98b

camera: Don't segfault if we get a NULL parameter

 * Values end up NULL on some drivers, don't crash.

Change-Id: Ic897dbd4629cf3af98c85f93be202c382dde806b

libstagefright: Support YVU420SemiPlanar camera format

Change-Id: I631ba6267b3769d9da498329a39ac89c609be6d8

stagefright: omx: Don't signal dataspace change on legacy QCOM

This isn't supported in legacy media HAL, and causes things like
screen recording and wifi display to fail when setting up the encoder.

This commit squashes:
  stagefright: omx: Rename legacy defaults to match lineage soong variable
  Change-Id: I783f75b2a6aea5b4f5619038888db394028e2010

Change-Id: Icb3f7b7dfefcfd72939037241568f28c01fc11ed

stagefright: ACodec: Resolve empty vendor parameters usage

 * On devices where vendorKeys is empty, the status was left
    as kExtensionsUnchecked and would block getVendorParameters
    on a wrong loop of empty vendor keys

 * Instead, set the status to kExtensionsNone to validate
    the check and the empty vendor keys, matching the old
    behaviour without vendor keys in getPortFormat

Change-Id: Ic3bdc9454c6af8e5d41ab901d4156ccb62281974
Signed-off-by: Adrian DC <radian.dc@gmail.com>

libstagefright: Free buffers on observer died

If observer died while allocating buffers, component remains
in loaded state. In cleanup, it checks for idle state to
free the allocated buffers which leads to memory leak.
Hence explicitly calling free buffers to avoid memory leak.

Change-Id: Ia8bd21f161473a18be30ec0fd7ad84b9e8fd83ee

libstagefright: use 64-bit usage for native_window_set_usage

Since Android 8.1 native_window_set_usage has changed to use 64-bit int
for the usage parameter. Use of 32-bit signed integer as parameter does
implicit conversion which may cause unexpected behaviour.

This change fixes errors like:
GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0xffffffff00002000
GraphicBufferAllocator: Failed to allocate (1920 x 1080) layerCount 1 format 2141391875 usage ffffffff80402900: 3

Original 64-bit usage commit:
https://android.googlesource.com/platform/frameworks/native/+/cb496acbe593326e8d5d563847067d02b2df40ec

Change-Id: Ic38cbb41997df9f5a77b276ba77e90a59cb5ae8d

camera: include: Don't override possible overlayed header

 * If targets define a specific header path, then let it be the case
   and don't override it to avoid mismatched headers in the modules.

 * This only became an issue since O due to moved camera headers (commit e2b43843fd12783188edd2c54188ea8d26864788).

Change-Id: I6bf7d1da7448d71f7821d40501db971f837781db

camera/media: Support legacy HALv1 camera in mediaserver

Pre 7.0 camera HALv1 can not share its video buffers
across different processes, which requires us to
disable this security feature.

This change allows devices to re-integrate cameraserver
and mediaserver which is the first step to support older
prebuilt camera HALs. A follow-up change will add back
support for legacy buffer handling.

To enable:
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
media.stagefright.legacyencoder=true
media.stagefright.less-secure=true

Change-Id: I4fcc8907ea235b7e83af26122b4da97ca5117816

mediaserver: Update HALv1 dependencies for 8.1.0

 * Add libcameraservice shared library dependency
 * Add new libgui, android.hardware.camera.common@1.0
    and android.hardware.camera.provider@2.4 shared
    libraries and exported headers HAL dependencies

 * Match cameraserver HIDL additions and dependencies

 * When TARGET_HAS_LEGACY_CAMERA_HAL1 is set, the mediaserver
    includes CameraService.h but exported headers are missing

 * Error upon build due to missing libcameraservice linkage:
    fatal error: 'android/hardware/BnCameraService.h' file not found

mediaserver: Update HALv1 dependencies for 9.0.0

 * Disable active state UID validation for HAL1 devices

Change-Id: Ib6bb8a4e9ef18606c64e2dff13504d2eeaac13b1
Signed-off-by: Adrian DC <radian.dc@gmail.com>

Camera: check metadata type before releasing frame

Hidl method releaseRecordingFrameHandle fails for metadata
type other than kMetadataBufferTypeNativeHandleSource which
prevents older devices to record video.

Change-Id: I0e84883bdb636e965526ca1282216baef43e87e8

libstagefright: Fix memory leak due to lock timeout

Memory leak has occurred when freeBuffer tries to
acquire the lock which is acquired by freeNode and
not released. Due to lock timeout in freeBuffer,
buffers are never released.

CRs-Fixed: 2423296

Change-Id: I468a562a2d1c76ffc0e666c120a5bbbedece48d7

camera: Allow devices to load custom CameraParameter code

* Some devices need additional code to load their cameras. Add a hook
  for extra classes and symbols to be included.

Originally implemented in Android.mk at 38b27bf2e5079441358288402b38865ba7c1d9d6
Credit to Ethan Chen for original Android.mk implementation
Originally implemented via lineage product variable at 7398f91e051086bdd210a8bae0533f15fac1a37f
Credit to Rashed Abdel-Tawab for original product variable implementation

Change-Id: Iec667af2f0bfdb41f14df342cb128908244d7af0